import type { Visit, Site } from '../types';

// ─── Sites ─────────────────────────────────────────────────────────────────────

export const SEED_SITES: Site[] = [
  {
    id: 'site-001',
    name: 'Riverside Industrial Complex',
    address: '4400 Industrial Pkwy, Charlotte, NC 28206',
    industry: 'hvac',
    contactName: 'Derek Holt',
    contactPhone: '(704) 555-0182',
    riskScore: 78,
  },
  {
    id: 'site-002',
    name: 'Lakewood Apartments — Block C',
    address: '811 Lakewood Dr, Raleigh, NC 27603',
    industry: 'restoration',
    contactName: 'Sandra Kim',
    contactPhone: '(919) 555-0244',
    riskScore: 62,
  },
  {
    id: 'site-003',
    name: 'Metro Financial Tower',
    address: '200 S Tryon St, Charlotte, NC 28202',
    industry: 'insurance',
    contactName: 'Thomas Vargas',
    contactPhone: '(704) 555-0391',
    riskScore: 22,
  },
  {
    id: 'site-004',
    name: 'Sunbelt Distribution Center',
    address: '9050 Airport Rd, Greensboro, NC 27409',
    industry: 'manufacturing',
    contactName: 'Lisa Okafor',
    contactPhone: '(336) 555-0117',
    riskScore: 45,
  },
  {
    id: 'site-005',
    name: 'Cypress Commons HOA',
    address: '320 Cypress Creek Rd, Cary, NC 27519',
    industry: 'property',
    contactName: 'Bryan Tate',
    contactPhone: '(919) 555-0558',
    riskScore: 38,
  },
];

// ─── Visits ────────────────────────────────────────────────────────────────────

export const SEED_VISITS: Visit[] = [
  // ── Riverside Industrial — 5 visits, recurring compressor + refrigerant issues ──
  {
    id: 'v-001',
    siteId: 'site-001',
    siteName: 'Riverside Industrial Complex',
    siteAddress: '4400 Industrial Pkwy, Charlotte, NC 28206',
    timestamp: new Date(Date.now() - 120 * 86400000).toISOString(),
    technician: 'Mike Torres',
    type: 'inspection',
    status: 'resolved',
    industry: 'hvac',
    geo: { lat: 35.2271, lng: -80.8431, address: '4400 Industrial Pkwy, Charlotte, NC', capturedAt: new Date(Date.now() - 120 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-001', tag: 'HVAC-A1', type: 'Rooftop Unit', model: 'Trane XR15', condition: 'fair', notes: 'Compressor running hot' },
      { id: 'eq-002', tag: 'HVAC-A2', type: 'Rooftop Unit', model: 'Trane XR15', condition: 'good', notes: '' },
    ],
    issues: [
      { id: 'i-001', category: 'Compressor Failure', description: 'RTU-A1 compressor cycling irregularly, high amperage draw', severity: 'high', resolved: true },
    ],
    checklist: [
      { id: 'c-001', label: 'Inspect refrigerant levels', checked: true, required: true },
      { id: 'c-002', label: 'Check electrical connections', checked: true, required: true },
      { id: 'c-003', label: 'Clean condenser coils', checked: true, required: false },
    ],
    notes: 'Replaced capacitor on HVAC-A1. Compressor still suspect — recommend monitoring.',
    photos: [],
    duration: 90,
  },
  {
    id: 'v-002',
    siteId: 'site-001',
    siteName: 'Riverside Industrial Complex',
    siteAddress: '4400 Industrial Pkwy, Charlotte, NC 28206',
    timestamp: new Date(Date.now() - 85 * 86400000).toISOString(),
    technician: 'Mike Torres',
    type: 'service',
    status: 'resolved',
    industry: 'hvac',
    geo: { lat: 35.2271, lng: -80.8431, address: '4400 Industrial Pkwy, Charlotte, NC', capturedAt: new Date(Date.now() - 85 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-003', tag: 'HVAC-A1', type: 'Rooftop Unit', model: 'Trane XR15', condition: 'poor', notes: 'Compressor replaced under warranty' },
    ],
    issues: [
      { id: 'i-002', category: 'Compressor Failure', description: 'Compressor seized — full replacement required', severity: 'critical', resolved: true },
      { id: 'i-003', category: 'Refrigerant Leak', description: 'R-410A leak detected at service port', severity: 'high', resolved: true },
    ],
    checklist: [
      { id: 'c-004', label: 'Pressure test refrigerant lines', checked: true, required: true },
      { id: 'c-005', label: 'Verify warranty documentation', checked: true, required: true },
    ],
    notes: 'Compressor replaced. Refrigerant recharged to spec. System operational.',
    photos: [],
    duration: 240,
  },
  {
    id: 'v-003',
    siteId: 'site-001',
    siteName: 'Riverside Industrial Complex',
    siteAddress: '4400 Industrial Pkwy, Charlotte, NC 28206',
    timestamp: new Date(Date.now() - 45 * 86400000).toISOString(),
    technician: 'Jenna Park',
    type: 'emergency',
    status: 'resolved',
    industry: 'hvac',
    geo: { lat: 35.2271, lng: -80.8431, address: '4400 Industrial Pkwy, Charlotte, NC', capturedAt: new Date(Date.now() - 45 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-004', tag: 'HVAC-B3', type: 'Rooftop Unit', model: 'Carrier 50XC', condition: 'critical', notes: 'Newly failed unit' },
    ],
    issues: [
      { id: 'i-004', category: 'Compressor Failure', description: 'Building B RTU-B3 full shutdown, compressor burned out', severity: 'critical', resolved: true },
      { id: 'i-005', category: 'Refrigerant Leak', description: 'Secondary leak at condenser manifold', severity: 'high', resolved: false },
    ],
    checklist: [
      { id: 'c-006', label: 'Isolate failed unit', checked: true, required: true },
      { id: 'c-007', label: 'Verify backup ventilation', checked: true, required: true },
    ],
    notes: 'Third compressor incident this quarter. Strongly recommend full RTU replacement audit.',
    photos: [],
    duration: 180,
  },
  {
    id: 'v-004',
    siteId: 'site-001',
    siteName: 'Riverside Industrial Complex',
    siteAddress: '4400 Industrial Pkwy, Charlotte, NC 28206',
    timestamp: new Date(Date.now() - 18 * 86400000).toISOString(),
    technician: 'Mike Torres',
    type: 'follow-up',
    status: 'in-progress',
    industry: 'hvac',
    geo: { lat: 35.2271, lng: -80.8431, address: '4400 Industrial Pkwy, Charlotte, NC', capturedAt: new Date(Date.now() - 18 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-005', tag: 'HVAC-B3', type: 'Rooftop Unit', model: 'Carrier 50XC', condition: 'poor', notes: 'Pending permanent fix' },
    ],
    issues: [
      { id: 'i-006', category: 'Refrigerant Leak', description: 'Condenser manifold leak still active, temp patch holding', severity: 'high', resolved: false },
    ],
    checklist: [
      { id: 'c-008', label: 'Check temp repair integrity', checked: true, required: true },
      { id: 'c-009', label: 'Order replacement manifold', checked: false, required: true },
    ],
    notes: 'Temp fix holding but manifold needs full replacement. Parts ordered, ETA 2 weeks.',
    photos: [],
    duration: 60,
  },
  {
    id: 'v-005',
    siteId: 'site-001',
    siteName: 'Riverside Industrial Complex',
    siteAddress: '4400 Industrial Pkwy, Charlotte, NC 28206',
    timestamp: new Date(Date.now() - 3 * 86400000).toISOString(),
    technician: 'Jenna Park',
    type: 'inspection',
    status: 'open',
    industry: 'hvac',
    geo: { lat: 35.2271, lng: -80.8431, address: '4400 Industrial Pkwy, Charlotte, NC', capturedAt: new Date(Date.now() - 3 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-006', tag: 'HVAC-C1', type: 'Split System', model: 'Daikin DX17VSS', condition: 'fair', notes: '' },
    ],
    issues: [
      { id: 'i-007', category: 'Compressor Failure', description: 'Unit C1 showing early compressor wear symptoms', severity: 'medium', resolved: false },
    ],
    checklist: [
      { id: 'c-010', label: 'Vibration analysis', checked: true, required: true },
      { id: 'c-011', label: 'Amperage test', checked: true, required: true },
      { id: 'c-012', label: 'Inspect capacitor bank', checked: false, required: false },
    ],
    notes: 'Unit C1 showing early warning signs. Schedule preventive service within 30 days.',
    photos: [],
    duration: 75,
  },

  // ── Lakewood Apartments — 4 visits, recurring water intrusion ──
  {
    id: 'v-006',
    siteId: 'site-002',
    siteName: 'Lakewood Apartments — Block C',
    siteAddress: '811 Lakewood Dr, Raleigh, NC 27603',
    timestamp: new Date(Date.now() - 95 * 86400000).toISOString(),
    technician: 'Rachel Ng',
    type: 'inspection',
    status: 'resolved',
    industry: 'restoration',
    geo: { lat: 35.7796, lng: -78.6382, address: '811 Lakewood Dr, Raleigh, NC', capturedAt: new Date(Date.now() - 95 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-007', tag: 'PUMP-C2', type: 'Sump Pump', model: 'Zoeller M53', condition: 'fair', notes: '' },
    ],
    issues: [
      { id: 'i-008', category: 'Water Intrusion', description: 'Basement units 1C–4C showing moisture infiltration after rain', severity: 'high', resolved: true },
    ],
    checklist: [
      { id: 'c-013', label: 'Moisture meter readings', checked: true, required: true },
      { id: 'c-014', label: 'Photo document affected areas', checked: true, required: true },
      { id: 'c-015', label: 'Sump pump operational check', checked: true, required: true },
    ],
    notes: 'Waterproofing membrane on north wall showing cracks. Sealed with hydraulic cement.',
    photos: [],
    duration: 120,
  },
  {
    id: 'v-007',
    siteId: 'site-002',
    siteName: 'Lakewood Apartments — Block C',
    siteAddress: '811 Lakewood Dr, Raleigh, NC 27603',
    timestamp: new Date(Date.now() - 62 * 86400000).toISOString(),
    technician: 'Rachel Ng',
    type: 'service',
    status: 'resolved',
    industry: 'restoration',
    geo: { lat: 35.7796, lng: -78.6382, address: '811 Lakewood Dr, Raleigh, NC', capturedAt: new Date(Date.now() - 62 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-008', tag: 'DRAIN-C1', type: 'French Drain', model: 'Custom Install', condition: 'poor', notes: 'Clogged with sediment' },
    ],
    issues: [
      { id: 'i-009', category: 'Water Intrusion', description: 'French drain failure caused flooding in storage areas', severity: 'critical', resolved: true },
      { id: 'i-010', category: 'Mold Growth', description: 'Mold colonies identified in 2C utility closet', severity: 'high', resolved: true },
    ],
    checklist: [
      { id: 'c-016', label: 'Air quality test', checked: true, required: true },
      { id: 'c-017', label: 'Remediation scope documented', checked: true, required: true },
    ],
    notes: 'French drain cleared and relaid. Mold remediation completed. Drywall replaced in 2C.',
    photos: [],
    duration: 360,
  },
  {
    id: 'v-008',
    siteId: 'site-002',
    siteName: 'Lakewood Apartments — Block C',
    siteAddress: '811 Lakewood Dr, Raleigh, NC 27603',
    timestamp: new Date(Date.now() - 28 * 86400000).toISOString(),
    technician: 'Carlos Vega',
    type: 'emergency',
    status: 'in-progress',
    industry: 'restoration',
    geo: { lat: 35.7796, lng: -78.6382, address: '811 Lakewood Dr, Raleigh, NC', capturedAt: new Date(Date.now() - 28 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-009', tag: 'PUMP-C2', type: 'Sump Pump', model: 'Zoeller M53', condition: 'critical', notes: 'Sump pump failed during storm' },
    ],
    issues: [
      { id: 'i-011', category: 'Water Intrusion', description: 'Sump pump failure during heavy storm — 3 units affected', severity: 'critical', resolved: false },
      { id: 'i-012', category: 'Structural Damage', description: 'Water damage to subfloor in unit 3C', severity: 'high', resolved: false },
    ],
    checklist: [
      { id: 'c-018', label: 'Emergency pump deployment', checked: true, required: true },
      { id: 'c-019', label: 'Tenant notification', checked: true, required: true },
      { id: 'c-020', label: 'Insurance documentation', checked: false, required: true },
    ],
    notes: 'Third water event at this property. Recommend full drainage system redesign.',
    photos: [],
    duration: 200,
  },
  {
    id: 'v-009',
    siteId: 'site-002',
    siteName: 'Lakewood Apartments — Block C',
    siteAddress: '811 Lakewood Dr, Raleigh, NC 27603',
    timestamp: new Date(Date.now() - 7 * 86400000).toISOString(),
    technician: 'Rachel Ng',
    type: 'follow-up',
    status: 'open',
    industry: 'restoration',
    geo: { lat: 35.7796, lng: -78.6382, address: '811 Lakewood Dr, Raleigh, NC', capturedAt: new Date(Date.now() - 7 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-010', tag: 'PUMP-C3', type: 'Sump Pump', model: 'Zoeller M98', condition: 'good', notes: 'New replacement pump' },
    ],
    issues: [
      { id: 'i-013', category: 'Structural Damage', description: 'Subfloor assessment in progress — extent TBD', severity: 'high', resolved: false },
    ],
    checklist: [
      { id: 'c-021', label: 'Moisture content survey', checked: true, required: true },
      { id: 'c-022', label: 'Subfloor probe test', checked: false, required: true },
      { id: 'c-023', label: 'Scope repair estimate', checked: false, required: false },
    ],
    notes: 'New sump pump installed. Subfloor damage assessment ongoing.',
    photos: [],
    duration: 90,
  },

  // ── Metro Financial Tower — 3 inspections, low risk ──
  {
    id: 'v-010',
    siteId: 'site-003',
    siteName: 'Metro Financial Tower',
    siteAddress: '200 S Tryon St, Charlotte, NC 28202',
    timestamp: new Date(Date.now() - 180 * 86400000).toISOString(),
    technician: 'Jenna Park',
    type: 'inspection',
    status: 'resolved',
    industry: 'insurance',
    geo: { lat: 35.2271, lng: -80.8432, address: '200 S Tryon St, Charlotte, NC', capturedAt: new Date(Date.now() - 180 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-011', tag: 'FSYS-F1', type: 'Fire Suppression', model: 'Tyco LFII', condition: 'good', notes: '' },
    ],
    issues: [],
    checklist: [
      { id: 'c-024', label: 'Sprinkler head inspection', checked: true, required: true },
      { id: 'c-025', label: 'Alarm pull station test', checked: true, required: true },
      { id: 'c-026', label: 'Extinguisher tags current', checked: true, required: true },
    ],
    notes: 'Annual fire suppression inspection. All systems compliant. Certificate issued.',
    photos: [],
    duration: 150,
  },
  {
    id: 'v-011',
    siteId: 'site-003',
    siteName: 'Metro Financial Tower',
    siteAddress: '200 S Tryon St, Charlotte, NC 28202',
    timestamp: new Date(Date.now() - 90 * 86400000).toISOString(),
    technician: 'Thomas Reyes',
    type: 'inspection',
    status: 'resolved',
    industry: 'insurance',
    geo: { lat: 35.2271, lng: -80.8432, address: '200 S Tryon St, Charlotte, NC', capturedAt: new Date(Date.now() - 90 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-012', tag: 'ELEC-P3', type: 'Electrical Panel', model: 'Square D QO', condition: 'good', notes: '' },
    ],
    issues: [
      { id: 'i-014', category: 'Electrical', description: 'Minor arc flash residue on panel door gasket — non-critical', severity: 'low', resolved: true },
    ],
    checklist: [
      { id: 'c-027', label: 'Panel torque check', checked: true, required: true },
      { id: 'c-028', label: 'Infrared scan of breakers', checked: true, required: true },
    ],
    notes: 'Quarterly electrical inspection. Minor arc trace cleaned. No actionable findings.',
    photos: [],
    duration: 100,
  },
  {
    id: 'v-012',
    siteId: 'site-003',
    siteName: 'Metro Financial Tower',
    siteAddress: '200 S Tryon St, Charlotte, NC 28202',
    timestamp: new Date(Date.now() - 10 * 86400000).toISOString(),
    technician: 'Jenna Park',
    type: 'inspection',
    status: 'resolved',
    industry: 'insurance',
    geo: { lat: 35.2271, lng: -80.8432, address: '200 S Tryon St, Charlotte, NC', capturedAt: new Date(Date.now() - 10 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-013', tag: 'FSYS-F1', type: 'Fire Suppression', model: 'Tyco LFII', condition: 'good', notes: '' },
    ],
    issues: [],
    checklist: [
      { id: 'c-029', label: 'Semi-annual flow test', checked: true, required: true },
      { id: 'c-030', label: 'Backflow preventer test', checked: true, required: true },
    ],
    notes: 'Semi-annual wet system test. All flows within spec. No deficiencies noted.',
    photos: [],
    duration: 120,
  },

  // ── Sunbelt Distribution Center — 2 visits ──
  {
    id: 'v-013',
    siteId: 'site-004',
    siteName: 'Sunbelt Distribution Center',
    siteAddress: '9050 Airport Rd, Greensboro, NC 27409',
    timestamp: new Date(Date.now() - 55 * 86400000).toISOString(),
    technician: 'Carlos Vega',
    type: 'inspection',
    status: 'resolved',
    industry: 'manufacturing',
    geo: { lat: 36.0726, lng: -79.792, address: '9050 Airport Rd, Greensboro, NC', capturedAt: new Date(Date.now() - 55 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-014', tag: 'CONV-L1', type: 'Conveyor System', model: 'Hytrol EZLogic', condition: 'good', notes: '' },
      { id: 'eq-015', tag: 'FORK-F3', type: 'Forklift', model: 'Toyota 8FGU25', condition: 'fair', notes: 'Minor hydraulic seep' },
    ],
    issues: [
      { id: 'i-015', category: 'Hydraulic System', description: 'Forklift F3 minor hydraulic fluid seepage at lift cylinder', severity: 'medium', resolved: true },
    ],
    checklist: [
      { id: 'c-031', label: 'Conveyor belt tension check', checked: true, required: true },
      { id: 'c-032', label: 'Forklift fluid levels', checked: true, required: true },
      { id: 'c-033', label: 'Safety barrier integrity', checked: true, required: true },
    ],
    notes: 'Quarterly equipment inspection. Hydraulic seal replaced on F3. Conveyor in good shape.',
    photos: [],
    duration: 130,
  },
  {
    id: 'v-014',
    siteId: 'site-004',
    siteName: 'Sunbelt Distribution Center',
    siteAddress: '9050 Airport Rd, Greensboro, NC 27409',
    timestamp: new Date(Date.now() - 14 * 86400000).toISOString(),
    technician: 'Mike Torres',
    type: 'service',
    status: 'in-progress',
    industry: 'manufacturing',
    geo: { lat: 36.0726, lng: -79.792, address: '9050 Airport Rd, Greensboro, NC', capturedAt: new Date(Date.now() - 14 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-016', tag: 'COMP-A1', type: 'Air Compressor', model: 'Ingersoll Rand R110i', condition: 'poor', notes: 'Pressure drop issues' },
    ],
    issues: [
      { id: 'i-016', category: 'Pneumatic System', description: 'Main air compressor losing pressure — affecting pneumatic tools on lines 2–4', severity: 'high', resolved: false },
    ],
    checklist: [
      { id: 'c-034', label: 'Leak detection survey', checked: true, required: true },
      { id: 'c-035', label: 'Pressure relief valve test', checked: false, required: true },
    ],
    notes: 'Multiple leaks found in distribution header. Partial repairs made, full header replacement scheduled.',
    photos: [],
    duration: 110,
  },

  // ── Cypress Commons HOA — 2 visits ──
  {
    id: 'v-015',
    siteId: 'site-005',
    siteName: 'Cypress Commons HOA',
    siteAddress: '320 Cypress Creek Rd, Cary, NC 27519',
    timestamp: new Date(Date.now() - 72 * 86400000).toISOString(),
    technician: 'Thomas Reyes',
    type: 'inspection',
    status: 'resolved',
    industry: 'property',
    geo: { lat: 35.7915, lng: -78.7811, address: '320 Cypress Creek Rd, Cary, NC', capturedAt: new Date(Date.now() - 72 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-017', tag: 'ROOF-B2', type: 'Roof System', model: 'TPO Membrane', condition: 'fair', notes: 'Minor ponding observed' },
    ],
    issues: [
      { id: 'i-017', category: 'Roofing', description: 'Ponding water on Building 2 flat roof section', severity: 'medium', resolved: true },
    ],
    checklist: [
      { id: 'c-036', label: 'Roof drain clear', checked: true, required: true },
      { id: 'c-037', label: 'Membrane seam inspection', checked: true, required: true },
    ],
    notes: 'Roof drains cleared of debris. Ponding resolved. Recommend annual inspection.',
    photos: [],
    duration: 80,
  },
  {
    id: 'v-016',
    siteId: 'site-005',
    siteName: 'Cypress Commons HOA',
    siteAddress: '320 Cypress Creek Rd, Cary, NC 27519',
    timestamp: new Date(Date.now() - 22 * 86400000).toISOString(),
    technician: 'Rachel Ng',
    type: 'service',
    status: 'resolved',
    industry: 'property',
    geo: { lat: 35.7915, lng: -78.7811, address: '320 Cypress Creek Rd, Cary, NC', capturedAt: new Date(Date.now() - 22 * 86400000).toISOString() },
    equipment: [
      { id: 'eq-018', tag: 'IRRIG-Z3', type: 'Irrigation System', model: 'Hunter Pro-C', condition: 'good', notes: '' },
    ],
    issues: [],
    checklist: [
      { id: 'c-038', label: 'Zone valve test', checked: true, required: true },
      { id: 'c-039', label: 'Head adjustment', checked: true, required: false },
      { id: 'c-040', label: 'Controller programming review', checked: true, required: false },
    ],
    notes: 'Spring irrigation startup complete. All 12 zones operational. Timer updated for DST.',
    photos: [],
    duration: 60,
  },
];
